### ISSUE TITLE
type 'Null' is not a subtype of type 'int' in type cast

### ISSUE THREAD

**Issue by Fadyio** [BirjuVachhani/target_mate#5]
I attempted to log in using both the username and password or API, but an error message appeared.
![Screenshot_20230401-081230](https://user-images.githubusercontent.com/76649269/229269199-f5f12f6f-c294-45e3-b750-2ba8b5b508e5.jpg)

**Comment by BirjuVachhani** [comment]
Hi @Fadyio,

Thank you for reporting this. Could you please provide following information about the issue?

1. Platform.
2. Version.
3. Sign-in method.

**Comment by Fadyio** [comment]
1. Android 11 Samsung phone 
2. Latest version from the play store or the GitHub release (I tried both, same problem)
3. Normal login with email and password and API ( again I tried both, same problem)

**Comment by Fadyio** [comment]
Hi, @BirjuVachhani, The issue seems to have been resolved after the last Play Store update. Thank you. I will leave a 5-star review for you.

**Comment by BirjuVachhani** [comment]
Thank you @Fadyio for your support. I hope you enjoy using it. 😊
